# Generated by Django 3.1 on 2020-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='google_id',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
