# Generated by Django 3.1 on 2020-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default=None, upload_to='listings'),
        ),
    ]
